# Generated by Django 6.0.2 on 2026-04-13 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='nota',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='usuarios.semestre', verbose_name='Semestre'),
        ),
        migrations.AddField(
            model_name='nota',
            name='tcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='api.tcp'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'tcp', 'semestre', 'asignatura')},
        ),
    ]
