# Generated by Django 6.0.2 on 2026-03-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='color',
            field=models.CharField(default='#000000', help_text='Código de color en formato HEX (ej: #FF5733)', max_length=7),
        ),
    ]
