# Generated by Django 6.0.2 on 2026-03-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_asignatura_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Semestre'),
        ),
    ]
